plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dbzbantenLS'
    compileSdk 33
    
    defaultConfig {
        applicationId "com.dbzbantenLS"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "2.0"
    }
    
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
    compileOnly 'de.robv.android.xposed:api:82:sources'
}